### ISSUE TITLE
How to use project .clang_complete file?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Rip-Rip/clang_complete#112]
The `:help clang_completion` documentation doesn't actually describe _what_ to put in a `.clang_completion` file. It just says “containing the compiler options,” which is opaque.
- Do I copy-paste the exact command-line into a single line in the `.clang_completion`?
- What about the linker command?
- Do I put a single library-name, as passed to `-l`, on each line?

I have no idea what to do, here.

**Comment by TermanEmil** [comment]
how can I include recursively?

**Comment by tibco-ranjan** [comment]
I resolved this problem by putting .clang_complete file in the root of my source project as stated in the
https://github.com/Rip-Rip/clang_complete link.

solution exmaple [centOS 7]
my project dir
root@localhost:~/LapiMyProg/CPP/DesingPatterns/CompoAggregAsscoc_bkp# ls -lart
total 12
-rw-r--r--. 1 root root 1639 Nov 17 16:33 main.cpp
drwxr-xr-x. 6 root root 125 Nov 17 16:39 ..
-rw-r--r--. 1 root root 2693 Nov 17 18:54 Makefile
drwxr-xr-x. 2 root root 18 Nov 17 18:57 Linux
-rw-r--r--. 1 root root 13 Nov 17 19:07 .clang_complete
drwxr-xr-x. 5 root root 103 Nov 17 19:07 .
drwxr-xr-x. 2 root root 156 Nov 17 19:09 include
drwxr-xr-x. 2 root root 164 Nov 17 19:12 source

Made an entry of my include folder in the .clang_complete file.
root@localhost:~/LapiMyProg/CPP/DesingPatterns/CompoAggregAsscoc_bkp# cat .clang_complete
-I./include/

In my include folder, I have put all my headers files as shown below.
In my source folder, I have put all my cpp files.
root@localhost:/LapiMyProg/CPP/DesingPatterns/CompoAggregAsscoc_bkp# cd include/
root@localhost:/LapiMyProg/CPP/DesingPatterns/CompoAggregAsscoc_bkp/include# ls
aggre_department.h aggreg_teacher.h assoc_doctor.h assoc_paitent.h common.h comp_house.h comp_room.h

Check if user-defined data types worked or not.
root@localhost:~/LapiMyProg/CPP/DesingPatterns/CompoAggregAsscoc_bkp# vim source/comp_house.cpp

std::ostream& operator<<(std::ostream& out, const House &house)
{
std::vector roomList = house.getRoomList();
roomList.pu
out<<"To push_back f void push_back(const std::vector<Room, std::allocator >::value_type &__x)
out<<"Name of the Rooms are" <<endl;
out<<"========================"<<endl;

    for(unsigned i=0; i< roomList.size(); i++)
    {
            roomList[i].DisplayRoom();
    };
    out<<"========================"<<endl;
    return out;
}

Result
As shown above

std::vector roomList = house.getRoomList();
roomList.

successfuly provides all the vector method (push_back)

Hope this will Help
