### ISSUE TITLE
E523 Error after attempting completion

### ISSUE THREAD

**Issue by digitalresistor** [Rip-Rip/clang_complete#115]
While attempting to auto complete, the quickfix window pops up with an error due to not being able to find a class I am using (due to a missing include), after this attempting to open a new buffer and fix the file does not work, no matter what I try I am unable to get back into insert mode giving me a very simple error:

```
E523: Not allowed here.
```

Which is not a whole lot of help.

I've disabled all plugins except for clang_complete and it still happens, as soon as it tries to auto complete on :: it pops open the quickfix window and disallows me from doing anything else that would result in going into insert mode.

Is there some way to reset vim so that it will allow me to go back into insert mode? I hate losing all my tabs and open files that I am working on due to clang_complete.

My .vimrc is available online at https://github.com/bertjwregeer/dotfiles/blob/master/vimrc

As a work-around at the moment I disabled the copen flag so it should no longer open the quickfix window.

**Comment by rookiepig** [comment]
Try this 
````
set completeopt-=preview
````
