### ISSUE TITLE
support for python 3

### ISSUE THREAD

**Issue by Mizuchi** [Rip-Rip/clang_complete#204]
Have plans to do a python3 support? I tried 2to3 but does not work.

**Comment by congee** [comment]
same issue on OSX 10.10.2 with clang bundled in Xcode

**Comment by tarikgraba** [comment]
Now in Debian testing, vim package is also compiled with only python3 support.

**Comment by graywolf** [comment]
that's a bold move, does debian have any reason for dropping the python2 support?

**Comment by tarikgraba** [comment]
Seems to be a decision of the package maintainer.
Here's a bug report about the suppressed feature on the official package tracker:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839903

**Comment by xaizek** [comment]
From the bug report:
> Both Python and Python3 can't be enabled at the same time, so one has to be chosen.

It's not true (`--enable-pythoninterp=dynamic --enable-python3interp=dynamic`):
```
$ src/vim --version | grep python
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
```

**Comment by tarikgraba** [comment]
Debian maintainer argues against loading python dynamically and has decided to switch from python2 to python3 with the release of Vim8

**Comment by xaizek** [comment]
So it doesn't work in Debian because of the way dependencies are managed and python is built there. Anyway, I just wanted to point out that Vim is able to do this in principle and "both Python and Python3 can't be enabled" is not the correct way of saying it.

**Comment by tarikgraba** [comment]
"both Python and Python3 can't be enabled" ... I never said that ;-)

**Comment by xaizek** [comment]
I know, they did. As for the issue, I think it should be possible to make the plugin compatible with both versions of python, but I don't have any experience doing this.

**Comment by jsfaint** [comment]
@xaizek 
In another issue session #430, @myint mentioned he add python 3 support for clang_complete.
but I'm not sure if his solution still compatible with the current clang_complete.

**Comment by xaizek** [comment]
Thanks @jsfaint, I forgot about that fork already. See `support-python3` branch. I didn't test it much, but it seems to work with both versions of python. After several people confirm that it works for them, we can merge it into `master`.

**Comment by jsfaint** [comment]
@xaizek It not works on macvim with the following config.
```
NeoBundle 'rip-rip/clang_complete', {'disabled': !(has('python') || has('python3'))}

"clang_complete
if neobundle#is_installed('clang_complete')
  let g:clang_auto_select = 1
  let g:clang_hl_errors = 1
  let g:clang_complete_copen = 1
  let g:clang_close_preview = 1

  if has('mac')
    let s:clang_library_path="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib"
    if isdirectory(s:clang_library_path)
      let g:clang_library_path=s:clang_library_path
    endif
  endif
endif
```

<img width="1389" alt="default" src="https://cloud.githubusercontent.com/assets/571829/21187460/019ec466-c253-11e6-9ead-e58f6d8b4352.png">

I'll try it on windows tomorrow.

**Comment by xaizek** [comment]
@jsfaint, thanks, missed useful change for `sorted()` builtin. Updated the branch.

**Comment by jsfaint** [comment]
@xaizek Thanks for your quick fix, it works now 👍

**Comment by tarikgraba** [comment]
I have not done intensive tests but it seems to work with vim8 on Debian testing.
THX for the fix.

**Comment by jsfaint** [comment]
Hi @xaizek I already use `support-python3` branch for daily work over 1 month, everything works well.

But I noticed a little thing, when using the `support-python3` branch, the command-line will print some message which is not happen in the master.
![image](https://cloud.githubusercontent.com/assets/571829/22230050/6b1ae234-e216-11e6-8a5d-0c3270c0e499.png)
Maybe it's some debugging message?

And another question, do you have any plan to merge `support-python3` into `master` branch?
Thank you~

**Comment by xaizek** [comment]
@Jsfaint, thanks, that was indeed a debug print statement that I forgot to remove, thanks. Removed that and merged it into `master`.

**Comment by jsfaint** [comment]
@xaizek Thank you~ 👍
