### ISSUE TITLE
Libclang can not find the builtin includes.

### ISSUE THREAD

**Issue by Urich** [Rip-Rip/clang_complete#238]
After open cpp file i did see message "WARNING: libclang can not find the builtin includes." etc. I did find wrong in function "getBuiltinHeaderPath". I did replace value path (library_path + "/../lib/clang") on this "library_path + "/../clang""
Value is library_path = /usr/lib/llvm

ps. Linux 3.3.8-gentoo

**Comment by dnery** [comment]
This problem popped up for me after updating clang to 3.8.0, the `clang` folder probably changed it's internal layout and messed up the script. I think I solved the problem on my end...

The bug in the script is when defining `subDir`. You see, retrieving from `files[-1]` will render, in my case, an executable (`ccc-analyzer`, specifically), because `sorted` will put the directory I want in the first position, not the last (`sorted` won't even change `files` array, actually). I ran an interactive test:

```
revenant% python2
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> path = "/../lib/clang" # library_path is initially empty, so it's safe to assume this will be first value...
>>> import os
>>> files = os.listdir(path)
>>> print files
['3.8.0', 'c++-analyzer', 'ccc-analyzer']
>>> files = sorted(files) # Needed, but changes nothing here. '3.8.0' is the dir I want...
>>> print files
['3.8.0', 'c++-analyzer', 'ccc-analyzer']
>>> wrongSubDir = files[-1] # What I'm getting...
>>> wrongSubDir
'ccc-analyzer'
>>> correctSubDir = files[0] # What I want...
>>> correctSubDir
'3.8.0'
>>> quit()
```
So, effectively, all I had to do was change the `-1` index to `0` when retrieving from `files` array. The function, now, becomes this:
```python
def getBuiltinHeaderPath(library_path):
  if os.path.isfile(library_path):
    library_path = os.path.dirname(library_path)

  knownPaths = [
          library_path + "/../lib/clang",  # default value
          library_path + "/../clang",      # gentoo
          library_path + "/clang",         # opensuse
          library_path + "/",              # Google
          "/usr/lib64/clang",              # x86_64 (openSUSE, Fedora)
          "/usr/lib/clang"
  ]

  for path in knownPaths:
    try:
      files = os.listdir(path)
      if len(files) >= 1:
        files = sorted(files)
        subDir = files[0]
      else:
        subDir = '.'
      path = path + "/" + subDir + "/include/"
      arg = "-I" + path
      if canFindBuiltinHeaders(index, [arg]):
        return path
    except:
      pass

  return None
```
I can't assume that the internal layout of the `clang` folder is, now, the same for everyone, but this did the trick for me. If this is, in fact, a solution, then I suggest a contributor updates it (I don't think a pull request is necessary).

Anyways, this is what it took me, so makes sense to let everyone else know... I've just that feeling that a lot are having the same problem I ~~was~~ am.

**Comment by AriaAsuka** [comment]
@ dnery
I came across this issue too, your solution works.

**Comment by dnery** [comment]
@AriaAsuka I made a pull-request with an equivalent solution. In my previous proposal I'm considering that there are no other subdirectories named after a version of clang; I noticed that simply reversing the ordering of the `files` array before defining `subDir` is a more robust solution. The aforementioned fix is #490, maybe this issue can finally be closed.

**Comment by deffi420** [comment]
@dnery I think your fix is wrong (see my comments in your PR #490).

My fix: PR #491

**Comment by dnery** [comment]
@deffi420 it is, indeed. #491 patches this issue properly.

**Comment by tibco-ranjan** [comment]
I solve this issue by following below steps. (CentOS -7)
1. Install clang-complete from rip-rip.
https://github.com/Rip-Rip/clang_complete

2. Done following entries in ~/.vimrc
" path to directory where library can be found
let g:clang_library_path='/usr/lib/clang-private/'
let g:clang_user_options='|| exit 0'
let g:clang_complete_auto = 1
let g:clang_complete_copen = 1
let g:clang_debug = 1

3. After installation, I got the clang-complete library in the folder "/usr/lib/clang-private/"
root@localhost:~/.vim/plugin# ls -lrt /usr/lib/clang-private/
total 34336
-rwxr-xr-x. 1 root root 2846788 Apr 11  2018 libclangStaticAnalyzerCheckers.so.5.0.0
-rwxr-xr-x. 1 root root  930224 Apr 11  2018 libclangParse.so.5.0.0
-rwxr-xr-x. 1 root root  621252 Apr 11  2018 libclangToolingRefactor.so.5.0.0
-rwxr-xr-x. 1 root root   69024 Apr 11  2018 libclangToolingCore.so.5.0.0
-rwxr-xr-x. 1 root root 1334448 Apr 11  2018 libclangStaticAnalyzerCore.so.5.0.0
-rwxr-xr-x. 1 root root  530736 Apr 11  2018 libclang.so.5.0
-rwxr-xr-x. 1 root root 1675192 Apr 11  2018 libclangSerialization.so.5.0.0
-rwxr-xr-x. 1 root root 7506328 Apr 11  2018 libclangSema.so.5.0.0
-rwxr-xr-x. 1 root root   64508 Apr 11  2018 libclangRewrite.so.5.0.0
-rwxr-xr-x. 1 root root  305496 Apr 11  2018 libclangIndex.so.5.0.0
-rwxr-xr-x. 1 root root   22896 Apr 11  2018 libclangFrontendTool.so.5.0.0
-rwxr-xr-x. 1 root root   65064 Apr 11  2018 libclangEdit.so.5.0.0
-rwxr-xr-x. 1 root root 2194228 Apr 11  2018 libclangARCMigrate.so.5.0.0
-rwxr-xr-x. 1 root root  214440 Apr 11  2018 libclangStaticAnalyzerFrontend.so.5.0.0
-rwxr-xr-x. 1 root root  490744 Apr 11  2018 libclangRewriteFrontend.so.5.0.0
-rwxr-xr-x. 1 root root  752560 Apr 11  2018 libclangLex.so.5.0.0
-rwxr-xr-x. 1 root root 1227244 Apr 11  2018 libclangFrontend.so.5.0.0
-rwxr-xr-x. 1 root root 1436748 Apr 11  2018 libclangDynamicASTMatchers.so.5.0.0
-rwxr-xr-x. 1 root root 1405400 Apr 11  2018 libclangDriver.so.5.0.0
-rwxr-xr-x. 1 root root 4083752 Apr 11  2018 libclangCodeGen.so.5.0.0
-rwxr-xr-x. 1 root root 2001524 Apr 11  2018 libclangBasic.so.5.0.0
-rwxr-xr-x. 1 root root 3416144 Apr 11  2018 libclangAST.so.5.0.0
-rwxr-xr-x. 1 root root  343120 Apr 11  2018 libclangTooling.so.5.0.0
-rwxr-xr-x. 1 root root  505440 Apr 11  2018 libclangFormat.so.5.0.0
-rwxr-xr-x. 1 root root  440388 Apr 11  2018 libclangASTMatchers.so.5.0.0
-rwxr-xr-x. 1 root root  629208 Apr 11  2018 libclangAnalysis.so.5.0.0

4. I didn't getany llvm library, as I had no clang installed on my system.

5. Installed clang
yum install -y clang.

6. Added the llvm and clang-private lib path in the "libclang.py" script as shown below.

root@localhost:~/.vim/plugin# ls
clang  clang_complete.vim  kinds.py  kinds.pyc  libclang.py  snippets

 knownPaths = [
          library_path + "/../lib/clang",  # default value
          library_path + "/../clang",      # gentoo
          library_path + "/clang",         # opensuse
          library_path + "/",              # Google
          "/usr/lib64/clang",              # x86_64 (openSUSE, Fedora)
          "/usr/lib/clang" ,
          "/usr/lib/clang-private" ,
          "/usr/lib/llvm"
  ]

7. Open any cpp file, the warning message didn't appread
"WARNING: libclang can not find the builtin includes." [GONE ha ha ha.............]

#include<iostream>
#include<vector>

using namespace std;

int main()
{
        std::vector<int> vec;
        vec.
            at                     f std::vector<int, std::allocator<int> >::reference at(std::vector::size_type __n)
}           reserve                f void reserve(std::vector::size_type __n)
~           erase                  f std::vector<int, std::allocator<int> >::iterator erase(std::vector<int, std::allocator<int> >::iter
~           erase                  f std::vector<int, std::allocator<int> >::iterator erase(std::vector<int, std::allocator<int> >::iter
~           operator[]             f std::vector<int, std::allocator<int> >::reference operator[](std::vector::size_type __n)
~           insert                 f std::vector<int, std::allocator<int> >::iterator insert(std::vector<int, std::allocator<int> >::ite
~           insert                 f void insert(std::vector<int, std::allocator<int> >::iterator __position, std::vector::size_type __n
~           pop_back               f void pop_back()
~           push_back              f void push_back(const std::vector<int, std::allocator<int> >::value_type &__x)
~           data                   f std::vector<int, std::allocator<int> >::pointer data()
~           back                   f std::vector<int, std::allocator<int> >::reference back()
~           front                  f std::vector<int, std::allocator<int> >::reference front()
~           operator=              f std::vector<int, std::allocator<int> > & operator=(const std::vector<int, std::allocator<int> > &__
~           ~vector                ~ void ~vector()
~           swap                   f void swap(std::vector<int, std::allocator<int> > &__x)
~           _M_fill_initialize     f void _M_fill_initialize(std::vector::size_type __n, const std::vector<int, std::allocator<int> >::v
~           clear                  f void clear()

---------------------
Hope this will help
----------------------
