### ISSUE TITLE
Make clang_complete work with -std=c++11

### ISSUE THREAD

**Issue by alfaBetaFoo** [Rip-Rip/clang_complete#326]
I'm fairly new to vim but I managed to install and run clang_complete inside vim quite easily because I'm not new to clang/llvm and compilers in general, The problem is that I don't understand how to tune the settings of clang_complete and if what I'm experiencing is a bug or not.

So, I have clang_complete up and running in vim and I need C++ 11 support, after reading some docs and some post online I understand that I should probably set something in 

```
~/.vim/plugin/clang_complete.vim
```

and I have done it with

```
let b:clang_user_options = '-std=c++11' 
```

Now clang_complete is still working but i don't have any C++11 keyword or method available, for example I'm trying this snippet and but it doesn't complete after `std::mt` not even with an explicit C-X C-U command and it gives me an error about `User defined completion Pattern not found`

```
#include <iostream>
#include <random>
#include <map>

int main()
{
  std::mt
}
```

How I can get C++ 11 features with clang_complete ?

**Comment by tibco-ranjan** [comment]
It worked perfectly well for me, after adding   [ let g:clang_user_options="-std=c++0x" ] in 
~/.vim/plugin/clang_complete.vim file as shown below.

root@localhost:~# cat ~/.vim/plugin/clang_complete.vim |grep -i "c++0x"
let g:clang_user_options="-std=c++0x"
.

        unique_ptr<Patient> ps1(new Patient("Dave"));

---------------------------------------------------------------------------
             operator= f Patient & operator=(const Patient &)
             operator= f Patient & operator=(Patient &&)
             ~Patient  ~ void ~Patient()
             addDoctor f void addDoctor(Doctor *doc)
             m_name    m std::string m_name
             m_doctor  m std::vector<Doctor *> m_doctor
             getName   f std::string getName()
             Patient   t Patient::
-----------------------------------------------------------------------------------
        ps1->
Note: The ps1 uniuqe_ptr now showing all the member function and variables of its class "Patient"
