### ISSUE TITLE
[FEATURE REQUEST] Add support for python3

### ISSUE THREAD

**Issue by adam900710** [Rip-Rip/clang_complete#430]
Since python3 is becoming default python in more and more distros,
what about support vim which enables +python3 ?

Thanks

**Comment by myint** [comment]
I've created a fork with Python 3 support:

https://github.com/myint/clang_complete

I've only minimally tested it so far.

**Comment by congee** [comment]
@myint Hey, buddy. Thank you very much.

**Comment by Anthony25** [comment]
@myint Thanks a lot, no problem with your fork for now !
