### ISSUE TITLE
use <C-g> to cancel complete-popup cause <cr> unmaped, then <cr> cannot use again

### ISSUE THREAD

**Issue by imzhangwenrong** [Rip-Rip/clang_complete#436]
in this case, if press 'enter', vim will input [ 54 'SNR' HandlePossibleSelectionEnter() ]

**Comment by wilywampa** [comment]
See https://github.com/Rip-Rip/clang_complete/issues/431

**Comment by xaizek** [comment]
It should be fixed now that fix for #431 is merged. Feel free to reopen if not.
