### ISSUE TITLE
error when installed from vundle

### ISSUE THREAD

**Issue by nickdesaulniers** [Rip-Rip/clang_complete#442]
I've installed this package via vundle.

When I type a dot after an instance of an object, I get:
```
Error detected while processing function ClangComplete:
line   22:
Traceback (most recent call last):
```

and when vim starts for a cpp file, I see a quick flash:
![screen_shot_2015-02-06_at_10_11_18_am](https://cloud.githubusercontent.com/assets/1823839/6084771/b0c3f8b6-ade8-11e4-8ff8-b1f03b644715.png)

**Comment by nickdesaulniers** [comment]
possible duplicate #264 ?

**Comment by xaizek** [comment]
> possible duplicate #264 ?

Probably not, the last error is the result of the first one, which is different issue in your case.

I'm not sure what that error means, but if you run `python` and type in `from ctypes import *` and get same errors, it's python issue. Otherwise maybe Vim uses wrong python and you could try running `:python from ctypes import *` in Vim, in which case it's Vim's issue. It looks like some python thing just fails, clang_complete doesn't do much at this point, but I might be wrong.

**Comment by nickdesaulniers** [comment]
When I run the import from python, no issue.  When I run it in Vim, I get:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/
__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/pytho
n2.7/lib-dynload/_ctypes.so, 2): Symbol not found: __PyInt_AsInt
  Referenced from: /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python
2.7/lib-dynload/_ctypes.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/_ctypes.so
```

From the readme:
```
You need Vim 7.3 or higher, compiled with python support and ideally, with
the conceal feature.
```

I _am_ running vim 7.3, but I don't remember ever compiling it from source, but it's not listed from `brew list | grep vim`, so maybe I did at one point.  `which vim` points to `/usr/bin/vim` and `la /usr/bin/vim` shows it as an exectuable, not a symlink, so I'm guessing I must still be using the default vim from OSX.  Maybe I should try building vim myself and try again?

**Comment by xaizek** [comment]
If you have `:python` command, you do have Vim compiled with python, but I have no idea what this `Cellar` is and whether python under that path is the one that comes with OSX (the one system Vim should be compiled against). Rebuilding Vim might help, but I'm really not sure.

**Comment by nickdesaulniers** [comment]
homebrew puts installed binaries in Cellars (homebrew has all this drink related metaphors; cellars, casks, taps).  Looks like I have a version of python installed with homebrew.  Let me try removing it real quick.

**Comment by nickdesaulniers** [comment]
Working well, thanks for the help @xaizek !  Quick question, now when I auto complete an additional window is opened on top that I don't know how to close.  Maybe if I knew more about vim, but any idea what this is or how I can prevent it or at least close it?
![screen shot 2015-02-06 at 1 12 35 pm](https://cloud.githubusercontent.com/assets/1823839/6087566/ff80ba02-ae01-11e4-9fb3-af3712cab09a.png)

**Comment by xaizek** [comment]
> Quick question, now when I auto complete an additional window is opened on top that I don't know how to close. Maybe if I knew more about vim, but any idea what this is or how I can prevent it or at least close it?

Try adding `let g:clang_close_preview = 1` or `set completeopt-=preview` to your `.vimrc`. Use <kbd>Ctrl-W O</kbd> to close all windows except the current one, <kbd>Ctrl-W C</kbd> works as `:q`, navigation is <kbd>Ctrl-W</kbd> followed by h/j/k/l.

**Comment by nickdesaulniers** [comment]
`set completeopt-=preview` worked well, thanks so much!
