### ISSUE TITLE
Can't find `limits.h` file even using libclang 3.6

### ISSUE THREAD

**Issue by albertnetymk** [Rip-Rip/clang_complete#444]
Clang 3.5 has a [bug](https://llvm.org/bugs/show_bug.cgi?id=19088) related to `limits.h`, and it's fixed, so using libclang 3.6 should be already. However, with the same test file from that bug report:

```
#include <limits.h>

int main() {
  return 0;
}
```

I still got the error:

```
/usr/include/limits.h|123 col 16 error| 'limits.h' file not found
```

Don't know much about python, but I still had a look at `plugin/libclang.py`.

Surprisingly, if I change the origial line from:

```
  currentFile = ("test.c", '#include "stddef.h"')
```

to:

```
  currentFile = ("test.c", '#include "limits.h"')
```

The error msg is gone, and it seems to work as usual. Anyone knowledgable enough care to elaborate?

**Comment by xaizek** [comment]
Code you changed is used to verify that include directory is correct. Maybe `stddef.h` causes false positive at least in your setup. I didn't like [that guessing](https://github.com/Rip-Rip/clang_complete/blob/master/plugin/libclang.py#L32-L39) ever, maybe `library_path + "/../lib64/clang",`  is missing from the list, but I'm really not sure.

**Comment by albertnetymk** [comment]
@xaizek What's the result with the above test program? Does it work or give the same error msg, `'limits.h' not found`?

**Comment by xaizek** [comment]
Seems to work as is here, but my system clang was `3.4.2`, so I updated it to `3.6.0`, which works as well. Maybe `libclang.so` you're using is left from `3.5.0` release?

**Comment by albertnetymk** [comment]
OK, that's weird. I am using xubuntu:
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```
`libclang.so` doesn't exist in `/usr/lib`, so I have to create the symlink myself:

```
$ ls -l /usr/lib/libclang.so
lrwxrwxrwx 1 root root 37 maj 20 18:20 /usr/lib/libclang.so -> /usr/lib/llvm-3.6/lib/libclang-3.6.so
```
I have removed `llvm-3.5` and `libclang1-3.5` two packages.

**Comment by egorutsov** [comment]
I have the same issue with libclang-3.6. I'm using Ubuntu Mate 15.04

**Comment by albertnetymk** [comment]
Using `clang version 3.9.1-svn288847-1~exp1 (branches/release_39)`, I can't reproduce it any more.
