### ISSUE TITLE
clang_complete file not being generated.

### ISSUE THREAD

**Issue by luisjomen2a** [Rip-Rip/clang_complete#447]
I am trying to use clang_complete on a really big project (lots of namespaces, lots of files), and have had no luck configuring the plugin.

I've followed numerous tutorials on generating the clang_complete file like http://www.guyrutenberg.com/2013/01/29/vim-creating-clang_complete-using-cmake/comment-page-1/#comment-1644496
and nothing is getting generated for me.

I have also tried to create this file manually and vim is just not taking it into account.

My `vimrc` has  the options : 
```vim
let g:clang_complete_copen=1
let g:clang_hl_errors=1
let g:clang_library_path = '/usr/lib/llvm-3.4/lib/libclang.so' 
```

Thank you guys, hope I get to use your amazing plugin!

**Comment by xaizek** [comment]
I recall something similar, please [take a look](http://stackoverflow.com/a/14633089/1535516).

> I have also tried to create this file manually and vim is just not taking it into account.

If you placed it at correct location (root of the project), then it should take effect.

`cc_args.py` writes file in directory in which build is performed, so if cmake switches it (e.g. to `build/`), you'll find the file there. It would be better to take destination path as an option in the script actually.

> Thank you guys, hope I get to use your amazing plugin!

Note that development has ceased over time, the plugin is still used, but doesn't get new features/bug fixes.

**Comment by graywolf** [comment]
> Note that development has ceased over time, the plugin is still used, but doesn't get new features/bug fixes.

Well I hope it won't stay like this forever :)

Anyway, this should probably be closed, it's old and no response from OP in more than a year.

**Comment by xaizek** [comment]
Yes, I think this is a usage issue, rather than something internal to plugin.
