### ISSUE TITLE
how to uninstall?

### ISSUE THREAD

**Issue by bubifengyun** [Rip-Rip/clang_complete#449]
Using Omnicppcomplete very long time, i like it. but i use

```bash
make install
```

i find that it pops 
> Loading libclang failed, completion won't be available. Consider setting g:clang_library_p
ath.

i don't know how to set the clang_library_path, and i want to uninstall it? how to uninstall?

**Comment by xaizek** [comment]
How about `make uninstall`?

**Comment by bubifengyun** [comment]
thank you. i find in Makefile
make uninstall
make clean
just OK, thank you.
