### ISSUE TITLE
Clang Complete Causing Vim to Display Incorrectly

### ISSUE THREAD

**Issue by cabellicar123** [Rip-Rip/clang_complete#453]
I use `clang_complete` with [`NeoBundle`](https://github.com/Shougo/neobundle.vim).

Vim version information:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 10 2015 04:51:12)
Included patches: 1-854
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib    
```

Before commenting out loading of `clang_complete`:
![screenshot from 2015-09-19 14-24-29](https://cloud.githubusercontent.com/assets/3083317/9977613/3cbf9380-5edc-11e5-8815-f06e6d2e799a.png)

After commenting out loading of `clang_complete`:
![screenshot from 2015-09-19 14-44-47](https://cloud.githubusercontent.com/assets/3083317/9977636/db49421c-5edc-11e5-862c-17b6e683826a.png)

**Comment by phi-gamma** [comment]
This is probably related with the most recent update to ncurses 6.0.
See also the forums: https://bbs.archlinux.org/viewtopic.php?id=202590

**Comment by Gaunah** [comment]
Same issue here. *bump for awareness*

**Comment by sdever** [comment]
Same issue here, however redirecting stderr to /dev/null seems to fix the problem (launch ``vim 2>/dev/null`` displays everything correctly, and clang-complete works as excepted).

**Comment by anatol** [comment]
@sdever Maybe stderr text can give better understanding what is going on. Could you please forward content of stderr to a file and post its content here?

**Comment by sdever** [comment]
Well I tried and got an empty file, which is very strange

Le jeu. 24 sept. 2015 à 11:08, Anatol Pomozov <notifications@github.com> a
écrit :

**Comment by jyelloz** [comment]
It seems that when stderr is a TTY then stdout (normal vim) gets messed up. I've tested this by redirecting stderr to a separate terminal window's pty. The normal vim terminal still got messed up. The best plan here to capture output might be to run `script -c 'vim test.c' bad-vim` and do a `:q`. Then run `script -c 'vim test.c 2>/dev/null' good-vim` and do a `:q`. Now the comparison between bad-vim and good-vim might show what is going wrong.
I did this and have some captures but GitHub seems to think powerpoint presentations are more important than text files containing escape sequences so here is a gist:
https://gist.github.com/jyelloz/4c4c1f40a314cf981537

**Comment by Hexcles** [comment]
Hi @jyelloz , I got the similar results by running strace on both good and bad vim and searched for `write(2, ` . Your approach is much better though!

I believe the major difference here is that when the output is a pty/tty, somehow many control characters (escape strings) are missing! Search for "NORMAL" in the output and you'll see. Usually there are some fancy magics/decorations around "NORMAL" (in status line), but in bad-vim these are all gone.

Both redirecting the output to a file and disabling clang-based plugins will solve the problem, which is super weird. These plugins, vim itself and clang haven't changed. The only new thing here is the ncurses. But somehow the new ncurses affects the behaviour of vim's output, and only when some clang-based plugins are used!

**Comment by rodrigorc** [comment]
It looks like a clang bug when managing the terminal colors. This hack fixes the issue by disabling them:

    diff --git a/plugin/clang/cindex.py b/plugin/clang/cindex.py
    index eb05560..bfeb58d 100644
    --- a/plugin/clang/cindex.py
    +++ b/plugin/clang/cindex.py
    @@ -1991,6 +1991,7 @@ class TranslationUnit(ClangObject):
             if args is None:
                 args = []
     
    +        args.append('-fno-color-diagnostics')
             if unsaved_files is None:
                 unsaved_files = []

**Comment by Hexcles** [comment]
It makes sense that color diagnostics has something to do with this bug, but the weird thing here is that the issue appears even when we open a new empty file and there's no output from clang yet.

**Comment by rodrigorc** [comment]
This was nagging me... Now I changed the hack above with:

    +        args.append('-fcolor-diagnostics')

(this activates the colors) and it works just the same...

So I've been debugging this a bit, through the clang code, and I think that I've finally discovered it 8-).

In file `./tools/clang/lib/Driver/Tools.cpp`, there is this code:

      enum { Colors_On, Colors_Off, Colors_Auto } ShowColors = Colors_Auto;
      //parse cmdline and assign ShowColors
      if (ShowColors == Colors_On ||
          (ShowColors == Colors_Auto && llvm::sys::Process::StandardErrHasColors()))

As you can see, `llvm::sys::Process::StandardErrHasColors()` is only called when the color diagnostics  is in **auto mode**. This function is in `lib/Support/Unix/Process.inc`:

    bool Process::StandardErrHasColors() {
      return FileDescriptorHasColors(STDERR_FILENO);
    }
    bool Process::FileDescriptorHasColors(int fd) {
      return FileDescriptorIsDisplayed(fd) && terminalHasColors(fd);
    }

And in the same file:

    static bool terminalHasColors(int fd) {
    #ifdef HAVE_TERMINFO
      // First, acquire a global lock because these C routines are thread hostile.
      MutexGuard G(*TermColorMutex);
    
      int errret = 0;
      if (setupterm((char *)nullptr, fd, &errret) != 0)
        // Regardless of why, if we can't get terminfo, we shouldn't try to print
        // colors.
        return false;
      [...]    
      // Now extract the structure allocated by setupterm and free its memory
      // through a really silly dance.
      struct term *termp = set_curterm((struct term *)nullptr);
      (void)del_curterm(termp); // Drop any errors here.
      [...]    
    }

Now, I'm not very used to curses programming, but I'm quite sure that this code will mess with any program that is already using curses, such as Vim, particularly the `del_curterm()` bit, because the `cur_term` is a curses global variable.

Now, IMO, the right way to do it would be to call `set_curterm()` before `setupterm()`: if it returns not-null then do not call `setupterm()` or `del_curterm()`; if it returns null then do as it is doing now.

**Comment by tobig** [comment]
On September 30, 2015 9:47:47 PM GMT+02:00, Rodrigo Rivas Costa <notifications@github.com> wrote:
>This was nagging me... Now I changed the hack above with:
>
>    +        args.append('-fcolor-diagnostics')
>
>(this activates the colors) and it works just the same...
>
>So I've been debugging this a bit, through the clang code, and I think
>that I've finally discovered it 8-).
>
>In file `./tools/clang/lib/Driver/Tools.cpp`, there is this code:
>
>  enum { Colors_On, Colors_Off, Colors_Auto } ShowColors = Colors_Auto;
>      //parse cmdline and assign ShowColors
>      if (ShowColors == Colors_On ||
>(ShowColors == Colors_Auto &&
>llvm::sys::Process::StandardErrHasColors()))
>
>As you can see, `llvm::sys::Process::StandardErrHasColors()` is only
>called when the color diagnostics  is in **auto mode**. This function
>is in `lib/Support/Unix/Process.inc`:
>
>    bool Process::StandardErrHasColors() {
>      return FileDescriptorHasColors(STDERR_FILENO);
>    }
>    bool Process::FileDescriptorHasColors(int fd) {
>      return FileDescriptorIsDisplayed(fd) && terminalHasColors(fd);
>    }
>
>And in the same file:
>
>    static bool terminalHasColors(int fd) {
>    #ifdef HAVE_TERMINFO
>// First, acquire a global lock because these C routines are thread
>hostile.
>      MutexGuard G(*TermColorMutex);
>    
>      int errret = 0;
>      if (setupterm((char *)nullptr, fd, &errret) != 0)
>// Regardless of why, if we can't get terminfo, we shouldn't try to
>print
>        // colors.
>        return false;
>      [...]    
>// Now extract the structure allocated by setupterm and free its memory
>      // through a really silly dance.
>      struct term *termp = set_curterm((struct term *)nullptr);
>      (void)del_curterm(termp); // Drop any errors here.
>      [...]    
>    }
>
>Now, I'm not very used to curses programming, but I'm quite sure that
>this code will mess with any program that is already using curses, such
>as Vim, particularly the `del_curterm()` bit, because the `cur_term` is
>a curses global variable.
>
>Now, IMO, the right way to do it would be to call `set_curterm()`
>before `setupterm()`: if it returns not-null then do not call
>`setupterm()` or `del_curterm()`; if it returns null then do as it is
>doing now.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Rip-Rip/clang_complete/issues/453#issuecomment-144519415

This analysis seems correct. Would you mind opening a Clang bug?

**Comment by rodrigorc** [comment]
> This analysis seems correct. Would you mind opening a Clang bug?

Done at https://llvm.org/bugs/show_bug.cgi?id=25007

**Comment by graywolf** [comment]
Is there some reason the `args.append('-fno-color-diagnostics')` isn't in this plugin? The clang bug is still open. Would it do any harm to include it in order to fix this in default configuration? I mean, do the colors actually do anything interesting for clang_complete? If yes, then as said `args.append('-fcolor-diagnostics')` works fine too.
