### ISSUE TITLE
STL vector of thread pointers not working

### ISSUE THREAD

**Issue by aressler38** [Rip-Rip/clang_complete#465]
I'm having trouble getting the auto complete to work with a vector of `std::thread*`.

    std::vector<int> v1;
    v1.<auto complete works!>
    std::vector<std::thread*> v2;
    v2.<auto complete doesn't work>

I followed setup instructions for vim found here: http://zwiener.org/vimautocomplete.html, and I'm also using the snipmate and super tab plugins described in the link, but I think this issue is related to clang_complete.

Does anyone have any ideas?

UPDATE:

the auto complete does work if I use a `typedef` as follows:

    typedef std::thread* thread_ptr;
    std::vector<thread_ptr> v;
    v.<auto complete works>

**Comment by xaizek** [comment]
Did you specify somewhere in your configuration that you need C++11 standard?

**Comment by aressler38** [comment]
I've not. What's the way to do that in my vimrc file?

**Comment by xaizek** [comment]
Try adding this setting:
```viml
let g:clang_user_options = '-std=c++11'
```

**Comment by aressler38** [comment]
That worked great! Thanks a lot. I couldn't find where options like that are listed.

**Comment by xaizek** [comment]
Options of clang_complete are in [docs](https://github.com/Rip-Rip/clang_complete/blob/master/doc/clang_complete.txt#L90). `-std=c++11` is a regular command-option for clang.
