### ISSUE TITLE
Uninstall clang_complete

### ISSUE THREAD

**Issue by eronde** [Rip-Rip/clang_complete#479]
Hi,

After testing clang_complete I would like to uninstall it.
To install clang_complete I've first cloned it and compiled it. Normally when you uninstall  a vim plugin you just remove the dir of the bundle directory. I've tried this with clang_complete, but when I open a new c file (new.c), the clang_complete plugin still opens.

How could I remove the clang_complete plugin completely?

**Comment by xaizek** [comment]
> compiled it

How (there is nothing to compile)? Maybe you mean `make install`? If yes, `make uninstall` should undo that.

**Comment by eronde** [comment]
Sorry, by compiled it  I meant make install. I've just removed removed the directory without doing make uninstall.

Thnx for the tip
