### ISSUE TITLE
Try to jump to definition before trying to go to the declaration in project

### ISSUE THREAD

**Issue by jcppkkk** [Rip-Rip/clang_complete#481]
An advanced case driven from #311 
Consider the following example:

**main.c**

```
#include "a.h"
int main(void)
{
    a(42);
}
```

**a.h**

```
static void a(int b);
```

**a.c**

```
static void a (int b) { }
```

We jumps to a.h now. Could we jumps to a.c instead?

(Possible duplicate to #134 )

**Comment by xaizek** [comment]
I don't think so. While in compilation-unit `main.c`, clang_complete knows nothing  about `a.c`  and can't navigate there. It needs a cross-unit database of symbols to be able to do that.

**Comment by jcppkkk** [comment]
@xaizek agree
