### ISSUE TITLE
How can i combine AutoComplete with clang_complete??

### ISSUE THREAD

**Issue by OsmanthusTree** [Rip-Rip/clang_complete#482]
I want to combine vim-autocomplpop with clang_complete
so that the completion will not be triggered manually any more.

But i just figured out an awkward way:
add `let g:acp_behaviorKeywordCommand = "\<C-x>\<C-u>"` to my vimrc

However, if the file i am editing is not c/cpp file, there are lots of errors which show the completefunc is not set ... How can i fix it ?? Thank you ...

**Comment by xaizek** [comment]
I didn't try it but maybe the following will work:
```vim
function! CompleteIfPossible()
    if empty(&completefunc)
        return ''
    endif
    return "\<C-x>\<C-u>"
endfunction
inoremap <expr> <c-x><c-g> CompleteIfPossible()
let g:acp_behaviorKeywordCommand = "\<C-x>\<C-g>"
```

**Comment by OsmanthusTree** [comment]
eh... It can not work properly ... when i am going to input `__list`, vim just shows ...
![screenshot from 2016-04-15 19-34-28](https://cloud.githubusercontent.com/assets/16307070/14560286/2bc4e256-0341-11e6-902d-3a6f6924b9b5.png)

**Comment by xaizek** [comment]
Maybe modify sources of vim-autocomplpop to add check like `if !empty(&completefunc)` where they invoke completion.

**Comment by OsmanthusTree** [comment]
Thank you very much ... But i had already find a proper way to fix it and it works really well.
After i read the manual of vim-autocomplete carefully, i found that i could change vim-autocomplete behavior by the following way... 

![screenshot from 2016-04-16 13-14-21](https://cloud.githubusercontent.com/assets/16307070/14579258/eaf367cc-03d4-11e6-8e43-7303e88b790e.png)
