### ISSUE TITLE
Slow completion

### ISSUE THREAD

**Issue by graywolf** [Rip-Rip/clang_complete#485]
I'm having problem with code completion being slow on each completion, not just the first one.. Possibly something line #17 ?

	$ LIBCLANG_TIMING=1 gvim engine/engine.h
	Parsing test.c:   0.0067 (100.0%)   0.0067 (100.0%)   0.0055 (100.0%)  
	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0037 (100.0%)  
	Parsing /home/paladin/stock/engine/engine.h:   0.6667 (100.0%)   0.0200 (100.0%)   0.6867 (100.0%)   0.6834 (100.0%)
	Reparsing /home/paladin/stock/engine/engine.h:   0.7133 (100.0%)   0.0167 (100.0%)   0.7300 (100.0%)   0.6726 (100.0%)
	Code completion @ /home/paladin/stock/engine/engine.h:37:5:   0.5033 (100.0%)   0.0333 (100.0%)   0.5367 (100.0%)   0.5036 (100.0%)
	Code completion @ /home/paladin/stock/engine/engine.h:37:5:   0.5000 (100.0%)   0.0133 (100.0%)   0.5133 (100.0%)   0.4981 (100.0%)

with `g:clang_debug=1` the `:mess` looks like this:

	Messages maintainer: Bram Moolenaar <Bram@vim.org>
	"engine/engine.h" 44L, 721C

	libclang code completion
	========================
	Command: clang -Wall -Wextra -Werror -std=c++11 -x c++ -I/usr/include -x c++-header -I/../lib/clang/3.9.0/include/ -fsyntax-only -Xclang -code-completion-at=/home/paladin/stock/engine/engine.h:37:5 /home/paladin/stock/engine/engine.h
	cwd: None
	File: /home/paladin/stock/engine/engine.h
	Line: 37, Column: 5

	^I^Il.

	libclang code completion -                    Get TU: 0.001s (  0.3%)
	libclang code completion -             Code Complete: 0.505s ( 92.1%)
	libclang code completion -      Count # Results (68): 0.002s (  0.4%)
	libclang code completion -                    Filter: 0.000s (  0.0%)
	libclang code completion -                      Sort: 0.007s (  1.2%)
	libclang code completion -                    Format: 0.030s (  5.5%)
	libclang code completion -       Load into vimscript: 0.003s (  0.5%)

	Overall: 0.548 s
	========================

	clang_complete: completion time 0.576719

	libclang code completion
	========================
	Command: clang -Wall -Wextra -Werror -std=c++11 -x c++ -I/usr/include -x c++-header -I/../lib/clang/3.9.0/include/ -fsyntax-only -Xclang -code-completion-at=/home/paladin/stock/engine/engine.h:37:5 /home/paladin/stock/engine/engine.h
	cwd: None
	File: /home/paladin/stock/engine/engine.h
	Line: 37, Column: 5

	^I^Il.

	libclang code completion -                    Get TU: 0.001s (  0.2%)
	libclang code completion -             Code Complete: 0.500s ( 95.3%)
	libclang code completion -      Count # Results (68): 0.001s (  0.1%)
	libclang code completion -                    Filter: 0.000s (  0.0%)
	libclang code completion -                      Sort: 0.001s (  0.2%)
	libclang code completion -                    Format: 0.019s (  3.6%)
	libclang code completion -       Load into vimscript: 0.003s (  0.5%)

	Overall: 0.524 s
	========================

	clang_complete: completion time 0.564625

I tried the `complete` test too and got:

	$ LIBCLANG_TIMING=1 ./complete ~/stock/engine/engine.h 37 5 -std=c++11 -I/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1 -I/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/backward -I/usr/local/include -I/usr/bin/../lib/clang/3.9.0/include -I/usr/include
	Parsing /home/paladin/stock/engine/engine.h:   0.6567 (100.0%)   0.0233 (100.0%)   0.6800 (100.0%)   0.6786 (100.0%)  
	Reparsing /home/paladin/stock/engine/engine.h:   0.6733 (100.0%)   0.0100 (100.0%)   0.6833 (100.0%)   0.6870 (100.0%)  
	Code completion @ /home/paladin/stock/engine/engine.h:37:5:   0.4900 (100.0%)   0.0167 (100.0%)   0.5067 (100.0%)   0.5042 (100.0%)  

Can someone help me with this? I'm not sure where could be the problem.

**Comment by graywolf** [comment]
Ok, issue resolved. I would call it borderline bug in clang, but whatever. With this code:

	#ifndef GUARD
	#define GUARD
	#include <string>
	#endif // GUARD

it's like this:

	$ LIBCLANG_TIMING=1 gvim engine/engine.h
	Parsing test.c:   0.0067 (100.0%)   0.0067 (100.0%)   0.0055 (100.0%)  
	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0037 (100.0%)  
	Parsing /home/paladin/stock/engine/engine.h:   0.6667 (100.0%)   0.0200 (100.0%)   0.6867 (100.0%)   0.6834 (100.0%)
	Reparsing /home/paladin/stock/engine/engine.h:   0.7133 (100.0%)   0.0167 (100.0%)   0.7300 (100.0%)   0.6726 (100.0%)
	Code completion @ /home/paladin/stock/engine/engine.h:37:5:   0.5033 (100.0%)   0.0333 (100.0%)   0.5367 (100.0%)   0.5036 (100.0%)

With this code:

	#include <string>
	#ifndef GUARD
	#define GUARD
	#endif // GUARD

it's like this:

	$ LIBCLANG_TIMING=1 gvim engine/engine.h
	Load: 0.79 0.80 0.45 , Memory: 12.68 %, Disk: 5.15 %
	   $ Parsing test.c:   0.0067 (100.0%)   0.0067 (100.0%)   0.0056 (100.0%)  
	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0056 (100.0%)  
	Parsing /home/paladin/stock/engine/engine.h:   0.6400 (100.0%)   0.0333 (100.0%)   0.6733 (100.0%)   0.6715 (100.0%)  
	Precompiling preamble:   0.7667 (100.0%)   0.0433 (100.0%)   0.8100 (100.0%)   0.8097 (100.0%)  
	Reparsing /home/paladin/stock/engine/engine.h:   0.8700 (100.0%)   0.0433 (100.0%)   0.9133 (100.0%)   0.9130 (100.0%)  
	Code completion @ /home/paladin/stock/engine/engine.h:37:5:   0.0567 (100.0%)   0.0567 (100.0%)   0.0546 (100.0%)  

So reading on how PCH in clang actually helped me to resolve this. On the other hand, it still is annoying.

Can something be done in clang_complete? I guess not, but doesn't hurt to ask.

**Comment by xaizek** [comment]
Hm, didn't expect that. I don't think there is anything the plugin can do. Messing with the source code being completed will probably yield wrong completions and I don't see other ways to affect behaviour of libclang (I guess forcing caching of includes separately won't work even if they provide this).

**Comment by graywolf** [comment]
Could  you please try if you have the same issue? I want to know if this is something specific to my install/my particular version of clang before I report it to LLVM bug tracker.

**Comment by xaizek** [comment]
Actually I get `Precompiling preamble: ...` for both samples on llvm 3.8.

**Comment by graywolf** [comment]
Since you said it all works for you, could you help me dig into it a bit deeper? I made few for tests, it's always source code then my `LIBCLANG_TIMING` output when I write `.` (dot) after `s` in main to trigger auto completion.

include-then-include-guard
--------------------------

Source:

	#include <string>

	#ifndef INC_GUARD
	#define INC_GUARD

	int main(int, char **) {
		std::string s;
		s
		return 0;
	}

	#endif /* end of include guard: INC_GUARD */

Output:

	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0067 (100.0%)   0.0053 (100.0%)  
	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0035 (100.0%)  
	Parsing /home/paladin/clang_complete_wrong/good.cpp:   0.2200 (100.0%)   0.0033 (100.0%)   0.2233 (100.0%)   0.2249 (100.0%)  
	Precompiling preamble:   0.3000 (100.0%)   0.0167 (100.0%)   0.3167 (100.0%)   0.3110 (100.0%)  
	Reparsing /home/paladin/clang_complete_wrong/good.cpp:   0.3133 (100.0%)   0.0167 (100.0%)   0.3300 (100.0%)   0.3266 (100.0%)  
	Code completion @ /home/paladin/clang_complete_wrong/good.cpp:8:4:   0.0267 (100.0%)   0.0267 (100.0%)   0.0264 (100.0%)  

include-guard-then-include
--------------------------

Source:

	#ifndef INC_GUARD
	#define INC_GUARD

	#include <string>

	int main(int, char **) {
		std::string s;
		s
		return 0;
	}

	#endif /* end of include guard: INC_GUARD */

Output:

	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0045 (100.0%)  
	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0035 (100.0%)  
	Parsing /home/paladin/clang_complete_wrong/good.cpp:   0.2100 (100.0%)   0.0133 (100.0%)   0.2233 (100.0%)   0.2236 (100.0%)  
	Reparsing /home/paladin/clang_complete_wrong/good.cpp:   0.2233 (100.0%)   0.2233 (100.0%)   0.2236 (100.0%)  
	Code completion @ /home/paladin/clang_complete_wrong/good.cpp:8:4:   0.1800 (100.0%)   0.0133 (100.0%)   0.1933 (100.0%)   0.1841 (100.0%)  

blank-line-then-include-guard-then-include
------------------------------------------

Source:

	// blank line
	#ifndef INC_GUARD
	#define INC_GUARD

	#include <string>

	int main(int, char **) {
		std::string s;
		s
		return 0;
	}

	#endif /* end of include guard: INC_GUARD */

Output:

	Parsing test.c:   0.0067 (100.0%)   0.0067 (100.0%)   0.0053 (100.0%)  
	Parsing test.c:   0.0033 (100.0%)   0.0033 (100.0%)   0.0052 (100.0%)  
	Parsing /home/paladin/clang_complete_wrong/good.cpp:   0.2167 (100.0%)   0.0033 (100.0%)   0.2200 (100.0%)   0.2185 (100.0%)  
	Precompiling preamble:   0.0233 (100.0%)   0.0033 (100.0%)   0.0267 (100.0%)   0.0277 (100.0%)  
	Reparsing /home/paladin/clang_complete_wrong/good.cpp:   0.2333 (100.0%)   0.0100 (100.0%)   0.2433 (100.0%)   0.2452 (100.0%)  
	Code completion @ /home/paladin/clang_complete_wrong/good.cpp:9:4:   0.2000 (100.0%)   0.0033 (100.0%)   0.2033 (100.0%)   0.1942 (100.0%)  



Conclusion
----------

I'm totally baffled by the results. Why does blank line cause the preamble to be compiled, but completion is still slow?

Could you please try all tree cases on your system and report back? If all three work for you fine (preample compiled && completion fast), I'll keep digging into my own system to find out where could be problem.

Thanks a lot :)

**Comment by xaizek** [comment]
This time my results seem to be match yours.

```
$ LIBCLANG_TIMING=1 gvim -f include-then-include-guard.cpp
Parsing test.c:   0.0010 (100.0%)   0.0010 (100.0%)   0.0007 (100.0%)
Parsing test.c:   0.0010 (100.0%)   0.0010 (100.0%)   0.0007 (100.0%)
Parsing .../include-then-include-guard.cpp:   0.0360 (100.0%)   0.0010 (100.0%)   0.0370 (100.0%)   0.0370 (100.0%)
Precompiling preamble:   0.0510 (100.0%)   0.0030 (100.0%)   0.0540 (100.0%)   0.0538 (100.0%)
Reparsing .../include-then-include-guard.cpp:   0.0550 (100.0%)   0.0030 (100.0%)   0.0580 (100.0%)   0.0572 (100.0%)
Code completion @ .../include-then-include-guard.cpp:8:7:   0.0080 (100.0%)   0.0080 (100.0%)   0.0079 (100.0%)
```

```
$ LIBCLANG_TIMING=1 gvim -f include-guard-then-include.cpp
Parsing test.c:   0.0010 (100.0%)   0.0010 (100.0%)   0.0007 (100.0%)
Parsing test.c:   0.0010 (100.0%)   0.0010 (100.0%)   0.0007 (100.0%)
Parsing .../include-guard-then-include.cpp:   0.0370 (100.0%)   0.0020 (100.0%)   0.0390 (100.0%)   0.0391 (100.0%)
Reparsing .../include-guard-then-include.cpp:   0.0380 (100.0%)   0.0380 (100.0%)   0.0382 (100.0%)
Code completion @ .../include-guard-then-include.cpp:8:7:   0.0850 (100.0%)   0.0040 (100.0%)   0.0890 (100.0%)   0.0875 (100.0%)
```

```
$ LIBCLANG_TIMING=1 gvim -f blank-line-then-include-guard-then-include.cpp
Parsing test.c:   0.0010 (100.0%)   0.0010 (100.0%)   0.0006 (100.0%)
Parsing test.c:   0.0007 (100.0%)
Parsing .../blank-line-then-include-guard-then-include.cpp:   0.0360 (100.0%)   0.0020 (100.0%)   0.0380 (100.0%)   0.0373 (100.0%)
Precompiling preamble:   0.0020 (100.0%)   0.0020 (100.0%)   0.0040 (100.0%)   0.0041 (100.0%)
Reparsing .../blank-line-then-include-guard-then-include.cpp:   0.0390 (100.0%)   0.0030 (100.0%)   0.0420 (100.0%)   0.0422 (100.0%)
Code completion @ .../blank-line-then-include-guard-then-include.cpp:9:7:   0.0280 (100.0%)   0.0010 (100.0%)   0.0290 (100.0%)   0.0283 (100.0%)
```

> I'm totally baffled by the results. Why does blank line cause the preamble to be compiled, but completion is still slow?

Yeah, that's weird. Seems like something related to heuristic for determining presence of header guard (maybe it doesn't expect anything before `#ifdef`).

**Comment by graywolf** [comment]
From quick peek the clang source code looks quite readable, will compile myself debug version and dig into it a bit.

**Comment by graywolf** [comment]
closing as I'm pretty sure this is bug inside clang, will follow up in it's code base
