### ISSUE TITLE
Remove warning for clang 3.8

### ISSUE THREAD

**Issue by adam900710** [Rip-Rip/clang_complete#486]
EDITED: 
Please remove the warning on slow completion after upgrading to clang 3.8.
```
"engine/engine.h" 44L, 722C
WARNING: libclang can not find the builtin includes.
         This will cause slow code completion.
         Please report the problem.

```
As I find the completion speed even improved a little.

ORIGINAL ISSUE:
Any idea on support for clang 3.8?

Some distro like arch is moving to clang 3.8, although it's still providing clang 3.5 for compatibility, but clang 3.5 will eventually fade out.

So is there any plan on support for clang 3.8?
Thanks

**Comment by graywolf** [comment]
Did you try it? I'm using Arch and even though `clang_complete` complains about

	"engine/engine.h" 44L, 722C
	WARNING: libclang can not find the builtin includes.
			 This will cause slow code completion.
			 Please report the problem.

it doesn't have any effect on completion speed (at least it doesn't seem to have). So I would say: "Works fine for me".

**Comment by adam900710** [comment]
Yes, completely the same output, and that's why I submitted this issue.

Except the warning, didn't see any slowdown though.(Maybe even a little faster?)

Then the bug is better to be renamed to "Remove warning for clang 3.8"?
