### ISSUE TITLE
Use ca_args.py without compiling whole project

### ISSUE THREAD

**Issue by Zouch** [Rip-Rip/clang_complete#495]
Is it possible to use ca_args.py without having to compile a whole project ? 
When I use `CXX='ca_args.py' cmake /path/to/cmakelists.txt` I got a CMake error, telling me that it can't compile a simple test program (which sounds ok I guess, but I'm wondering it there is a workaround).
This is a bit annoying when you want to generate .clang_complete if the code is already compiled and takes a while to recompile completly.

Thanks !

**Comment by tobig** [comment]
On 08/02/2016 04:31 PM, Charly Mourglia wrote:
> Is it possible to use ca_args.py without having to compile a whole
> project ?
> When I use |CXX='ca_args.py' cmake /path/to/cmakelists.txt| I got a
> CMake error, telling me that it can't compile a simple test program
> (which sounds ok I guess, but I'm wondering it there is a workaround).
> This is a bit annoying when you want to generate .clang_complete if the
> code is already compiled and takes a while to recompile completly.

Look for CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON and the
g:clang_compilation_database option.

This might help.

Best,
Tobias

**Comment by Zouch** [comment]
Sounds great, thanks !
