### ISSUE TITLE
How do you cycle through completions?

### ISSUE THREAD

**Issue by sittim** [Rip-Rip/clang_complete#499]
- How do you cycle through list of completions.

**Comment by xaizek** [comment]
What do you mean by "cycle"? The plugin provides list of matches, after that you pick completion from a generic completion menu where <kbd>Ctrl+N</kbd>, <kbd>Ctrl+P</kbd> and alike work and wrap around ends of list.

**Comment by sittim** [comment]
Thank you, I added pull request with your sentence added to readme.
