### ISSUE TITLE
Loading libclang failed, completion won't be available.

### ISSUE THREAD

**Issue by fishcop** [Rip-Rip/clang_complete#501]
Hey guys,

i just installed clang with 
git clone ....
cd clang...`
make install` 
into my ~/.vim/
and saved the extracted tarball from http://llvm.org/releases/download.html#3.9.0 , the pre-built binary for Arch64 linux(yes i use Arch linux 64bit) in ~/.clang
into my .vimrc i put:
"let g:clang_library_path='~/.clang/lib' ".
But even im 100% sure the "libclang.so" is there, at opening a .cpp file I get the error: 
"Loading libclang failed, completion won't be available. Are you sure '~/.clang/lib/' contains libclang?"

Do you have any ideas?

**Comment by xaizek** [comment]
Try changing
```vim
let g:clang_library_path='~/.clang/lib'
```
to
```vim
let g:clang_library_path=$HOME.'/.clang/lib' 
```
Vim or the plugin don't expand `~` in paths.

**Comment by fishcop** [comment]
Did this, but it has no effect at all.

**Comment by xaizek** [comment]
It should've at least changed the error message to do not mention path with `~` anymore.

**Comment by fishcop** [comment]
yes the path in  the error is updated to /home/arminusr/.clang/lib

**Comment by xaizek** [comment]
OK, so the change took effect. You did not download `Clang for AArch64 Linux`, right?

**Comment by fishcop** [comment]
This is excatly the package I downloaded

**Comment by xaizek** [comment]
It's not for Arch Linux x86_64, it's for AArch64, which is 64-bit ARM CPUs. I think you can use [this AUR package](https://aur.archlinux.org/packages/clang%2Bllvm-binaries/).

**Comment by graywolf** [comment]
@fishcop is there any particular reason not to use `extra/clang`? It works fine for me.

**Comment by fishcop** [comment]
@xaizek it  works now, thank you
@graywolf did not know about his existence
