### ISSUE TITLE
can't initialize properly if llvm was compiled with LLVM_BUILD_LLVM_DYLIB

### ISSUE THREAD

**Issue by muphil** [Rip-Rip/clang_complete#507]
Hi, 
clang_complete complains about:
```
Loading libclang failed, completion won't be available. Are you sure '/usr/lib' contains libclang?
```
libclang.so is under /usr/lib on the system,
Then I found out the issue occured inside `plugin/libclang.py:70`, after commenting out the exception handling of that line of code, I got:
```
File "/home/x/.vim/plugin/clang/cindex.py", line 3167, in get_cindex_library
    raise LibclangError(msg)
clang.cindex.LibclangError: libLLVMX86CodeGen.so: cannot open shared object file: No such file or directory. To provide a path to libclang use 
Config.set_library_path() or Config.set_library_file().
```
And I checked that indeed the system doesn't have libLLVMX86CodeGen.so, but it has libLLVMX86CodeGen.a, 
Apparently libLLVMx86CodeGen.so comes from llvm. This is how llvm was built by a package manager on my system:
```
  cmake -DLLVM_ENABLE_CXX1Y=1 \
    -DLLVM_INCLUDE_EXAMPLES=0 \
    -DLLVM_INCLUDE_TESTS=0 \
    -DLLVM_TARGETS_TO_BUILD='X86;AMDGPU;BPF' \
    -DLLVM_BUILD_LLVM_DYLIB=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr ..
```
So the problem is the option LLVM_BUILD_LLVM_DYLIB, according to http://llvm.org/docs/CMake.html, if that option is enabled, there would be one single shared library(libLLVM.so) instead of many.

Then I tried to set `let g:clang_library_path = '/usr/lib/libLLVM.so'`, but without luck, it gave me another error:
```
File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libLLVM.so: undefined symbol: clang_createIndex`
```
This time it can't find libclang.so. 

I think currently clang_complete requires llvm/clang to be built with BUILD_SHARED_LIBS, but not LLVM_BUILD_LLVM_DYLIB, 
According to the documentation of llvm, it is recommended to use LLVM_BUILD_LLVM_DYLIB instead.

So I think some chagnes need to be made in order for it to work properly with llvm/clang in this situation.

**Comment by muphil** [comment]
I'm sorry about the noise, the real problem is that the clang package was compiled with BUILD_SHARED_LIBS, and it deleted all llvm related files(include libLLVMX86CodeGen.so), while llvm links all shared libraries as libLLVM.so, so it couldn't find other shared libraries through libclang.so.

**Comment by j5shi** [comment]
Hi @muphil, could you please post your full script to build llvm? As I have exactly the same issue. Thanks!

**Comment by muphil** [comment]
@j5shi, Sure
```
cmake -DLLVM_ENABLE_CXX1Y=1 \
    -DLLVM_INCLUDE_EXAMPLES=0 \
    -DLLVM_INCLUDE_TESTS=0 \
    -DLLVM_TARGETS_TO_BUILD='X86;AMDGPU;BPF' \
    -DLLVM_BUILD_LLVM_DYLIB=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr ..
```

[llvm] http://crux.nu/ports/crux-3.2/opt/llvm/Pkgfile
[clang] https://crux.nu/ports/crux-3.2/opt/clang/Pkgfile
