### ISSUE TITLE
Python3 support issue.

### ISSUE THREAD

**Issue by golem0xE** [Rip-Rip/clang_complete#513]
Hello,
I have found an issue with python3. Attached please find a patch that seems to solve the problem.

Best regards,
Piotr
[0001-Python-3-adjustment.zip](https://github.com/Rip-Rip/clang_complete/files/775090/0001-Python-3-adjustment.zip)

**Comment by xaizek** [comment]
Thanks. Doesn't seem to break anything in my simple tests and looks reasonable.
