### ISSUE TITLE
generating .clang_complete with make

### ISSUE THREAD

**Issue by junhyeokahn** [Rip-Rip/clang_complete#516]
Hi, when I
CXX=”$HOME/.vim/bin/cc_args.py clang++” cmake ..
I returns
cc_args.py is not able to compile a simple test program.
and something like permission denied.

I would appreciate if you can help me

**Comment by xaizek** [comment]
Does running `$HOME/.vim/bin/cc_args.py clang++` in a shell work?

**Comment by junhyeokahn** [comment]
well, When I run the 
python cc_args.py clang++
in $HOME/.vim/bin/
it returns
<img width="976" alt="screen shot 2017-02-21 at 5 14 58 am" src="https://cloud.githubusercontent.com/assets/23005104/23162650/c1c463e6-f7f4-11e6-8eec-4200fc134194.png">

**Comment by xaizek** [comment]
You didn't pass it a parameter in the first case, hence the failure.

Tt shouldn't need `python`, just `./cc_args.py clang++`. It must be executable to work and your output says `Permission denied`, which hints that it isn't. Just do `chmod +x cc_args.py`.

**Comment by junhyeokahn** [comment]
I tried chmod command and now it doesn't return any permission deny.
Also Cmake, make works but it is not generating .clang_complete

**Comment by junhyeokahn** [comment]
Oh, I think it generate .clang_complete in  my generated file in build.
I thought with this .clang_complete file, when I use class in included file it should provide me some functions I can choose, but it doesn't provide what I want.
it works in terms of suggesting some functions but not in that class.

for example, when I type
class->
it suggests me some function(around 3000functions) which I've never used.
The function I want actually is what I defined in that class which is in included in there.

**Comment by junhyeokahn** [comment]
I got it!
Thank you so much!
:)
