### ISSUE TITLE
completion for python

### ISSUE THREAD

**Issue by junhyeokahn** [Rip-Rip/clang_complete#523]
Hi,
I am using clang_complete well in c++
Also I am now coding in python, but clang_complete is for c from my understanding.
And I am afraid if I download another completion like youcompleteme, it messed up c++ plugins.

Is there any recommendation for me?

**Comment by xaizek** [comment]
Hi,

I'd try using less universal plugin than youcompleteme like [jedi-vim](https://github.com/davidhalter/jedi-vim) or look up in youcompleteme documentation on how to disable it for specific filetypes.
