### ISSUE TITLE
How to autocomplete while writing ?

### ISSUE THREAD

**Issue by su8** [Rip-Rip/clang_complete#561]
Hello @Rip-Rip 

How to autocomplete/suggest for completion while writing, I don't want to press <kbd>CTRL</kbd>+<kbd>P/N</kbd> ? https://github.com/Shougo/neocomplete.vim already does this for most of the time, but it doesn't autocomplete functions/code that haven't been written in the window/buffers.

Cheers

**Comment by lifepillar** [comment]
You may try [MUcomplete](https://github.com/lifepillar/vim-mucomplete). The Readme has an example of configuration for clang_complete.

**Disclaimer:** I am the author of MUcomplete.

**Comment by su8** [comment]
Thanks @lifepillar !
