### ISSUE TITLE
what is MkVimball in the makefile

### ISSUE THREAD

**Issue by liushapku** [Rip-Rip/clang_complete#565]
I installed the plugin and then follow `readme.md` to do the installation. But after `make` or `make install` the file `clang_complete.vmb` is not generated.

I actually use `vim-plug` and `neovim`. So I also tried the following command

    Plug 'rip-rip/clang_complete', {'do': 'nvim -c \"r! git ls-files autoload bin doc plugin\" -c \"$$,$$d _\" -c \"%MkVimball! $@ .\" -c \"q!\" && nvim &< -c \"so %\" -c \"q\"' }

It doesn't work either

**Comment by xaizek** [comment]
With `vim-plug` you don't need that. neovim probably doesn't have vimball plugin. It's a plugin distribution/management mechanism, there is its documentation: https://vimhelp.appspot.com/pi_vimball.txt.html

**Comment by liushapku** [comment]
Thanks very much.
It would be much appreciated if you could also update the front page so
that others like me will not be trapped over there.

xaizek <notifications@github.com> 于 2018年9月18日周二 下午4:46写道：
